data = [
    {"Address":"Central 14",
     "Building_type":"noncombustible",
     "Square":"45 m^2",
     "Rooms":"2",
     "Balcony":"include",
     "Floor":"6",
     "Price":"12000 UAH/month",
     "src":"https://images.pexels.com/photos/7614605/pexels-photo-7614605.jpeg"
     },
    {"Address": "Central 14",
     "Building_type": "noncombustible",
     "Square": "45 m^2",
     "Rooms": "2",
     "Balcony": "include",
     "Floor": "6",
     "Price": "12000 UAH/month",
     "src": "https://images.pexels.com/photos/7614604/pexels-photo-7614604.jpeg"
     },
    {"Address": "Central 14",
     "Building_type": "noncombustible",
     "Square": "45 m^2",
     "Rooms": "2",
     "Balcony": "include",
     "Floor": "6",
     "Price": "12000 UAH/month",
     "src": "https://images.pexels.com/photos/8082193/pexels-photo-8082193.jpeg"
     },
     {"Address": "Central 14",
     "Building_type": "noncombustible",
     "Square": "45 m^2",
     "Rooms": "2",
     "Balcony": "include",
     "Floor": "6",
     "Price": "12000 UAH/month",
     "src": "https://images.pexels.com/photos/8089161/pexels-photo-8089161.jpeg"
     },
     {"Address": "Central 14",
     "Building_type": "noncombustible",
     "Square": "45 m^2",
     "Rooms": "2",
     "Balcony": "include",
     "Floor": "6",
     "Price": "12000 UAH/month",
     "src": "https://images.pexels.com/photos/7546558/pexels-photo-7546558.jpeg"
     },
     {"Address": "Central 14",
     "Building_type": "noncombustible",
     "Square": "45 m^2",
     "Rooms": "2",
     "Balcony": "include",
     "Floor": "6",
     "Price": "12000 UAH/month",
     "src": "https://images.pexels.com/photos/7546599/pexels-photo-7546599.jpeg"
     }
]